plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.linereadradar'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.linereadradar'
        minSdk 26
        targetSdk 35
        versionCode 10
        versionName '0.5.4-exp'
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
