plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.linereadradar'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.linereadradar'
        minSdk 26
        targetSdk 35
        versionCode 24
        versionName '0.6.9-shizuku'
    }

    buildFeatures {
        aidl true
        buildConfig true
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    implementation 'androidx.annotation:annotation:1.8.2'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    testImplementation 'junit:junit:4.13.2'
}
